# Generated by Django 4.1.3 on 2022-11-03 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fabrikanten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('build', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(choices=[('BENZINE', 'Benzine'), ('DIESEL', 'Diesel')], default='BENZINE', max_length=8)),
                ('fabrikanten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrikanten.fabrikanten')),
            ],
            options={
                'db_table': 'autos',
            },
        ),
    ]
