# Generated by Django 4.1.3 on 2022-11-01 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabrikanten', '0001_initial'),
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='fabrikanten',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fabrikanten.fabrikanten'),
            preserve_default=False,
        ),
    ]
